### ISSUE TITLE
Segfault when an Error is thrown in glutMainLoop()

### ISSUE THREAD

**Issue by Yogarine** [Ponup/phpopengl#10]
If a PHP error is throw (for example attempting to call an undeclared PHP function) it will result in glut segfaulting.

**Comment by santiagolizardo** [comment]
Glut is no longer part of this extension. All the Glut related code has been removed.
In order to create a window, GL context and capture events you would need an additional PHP extension: SDL.
[This example](https://github.com/Ponup/phpopengl/blob/master/examples/basic-shader.php) shows how to use PHP-SDL and PHP-OpenGL together.
